
names = ['Zarifjan', 'Shahla', 'Bilal', 'emine', 'hatije']
print(names)
names.append('murat')
print(names)
names.insert(0, 'Egemberdi')
print(names)
print(names[0])
print(names[-2].title())
print(names[1].upper())
print("Full Name : \n\t " + names[1] +" "+ names[0].upper() + "YEVICH")

del names[-1]
print(names)
names.remove('Shahla')
print(names)
deleted_name = names.pop(0)
print(names)
print(deleted_name)
names.sort(reverse=True)
print(names)
names.insert(0, 'Hatije')
names.insert(0, 'Emine')
deleted_name = names.pop(2)
deleted_name = names.pop(2)
names.sort(reverse=True)
names.reverse()
print(names)
print(deleted_name)